export type KnownTextureFormat =
  //from Android on HTC One M9
  | 'etc1.COMPRESSED_RGB_ETC1_WEBGL'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR'
  | 'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_12x12_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_12x10_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_10x10_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_10x8_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_10x6_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_10x5_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_8x8_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_8x6_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_8x5_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_6x6_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_6x5_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_5x5_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_5x4_KHR'
  | 'astc.COMPRESSED_RGBA_ASTC_4x4_KHR'

  //from OSX 10.14.4 on 2013 Macbook Pro
  | 's3tc.COMPRESSED_RGBA_S3TC_DXT5_EXT'
  | 's3tc.COMPRESSED_RGBA_S3TC_DXT3_EXT'
  | 's3tc.COMPRESSED_RGBA_S3TC_DXT1_EXT'
  | 's3tc.COMPRESSED_RGB_S3TC_DXT1_EXT'

  //from iOS on iPad Pro Mini
  | 'pvrtc.COMPRESSED_RGBA_PVRTC_2BPPV1_IMG'
  | 'pvrtc.COMPRESSED_RGBA_PVRTC_4BPPV1_IMG'
  | 'pvrtc.COMPRESSED_RGB_PVRTC_2BPPV1_IMG'
  | 'pvrtc.COMPRESSED_RGB_PVRTC_4BPPV1_IMG'

const KnownTextureFormatProxy: { [K in KnownTextureFormat]: 0 } = {
  'etc1.COMPRESSED_RGB_ETC1_WEBGL': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR': 0,
  'astc.COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_12x12_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_12x10_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_10x10_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_10x8_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_10x6_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_10x5_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_8x8_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_8x6_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_8x5_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_6x6_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_6x5_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_5x5_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_5x4_KHR': 0,
  'astc.COMPRESSED_RGBA_ASTC_4x4_KHR': 0,

  //from OSX 10.14.4 on 2013 Macbook Pro
  's3tc.COMPRESSED_RGBA_S3TC_DXT5_EXT': 0,
  's3tc.COMPRESSED_RGBA_S3TC_DXT3_EXT': 0,
  's3tc.COMPRESSED_RGBA_S3TC_DXT1_EXT': 0,
  's3tc.COMPRESSED_RGB_S3TC_DXT1_EXT': 0,

  //from iOS on iPad Pro Mini
  'pvrtc.COMPRESSED_RGBA_PVRTC_2BPPV1_IMG': 0,
  'pvrtc.COMPRESSED_RGBA_PVRTC_4BPPV1_IMG': 0,
  'pvrtc.COMPRESSED_RGB_PVRTC_2BPPV1_IMG': 0,
  'pvrtc.COMPRESSED_RGB_PVRTC_4BPPV1_IMG': 0
}

export const KnownTextureFormatStrings = Object.keys(KnownTextureFormatProxy)

export function isKnownTextureFormat(x: string): x is KnownTextureFormat {
  return KnownTextureFormatStrings.includes(x)
}
